# Generated by Django 4.1.2 on 2023-01-23 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FundamentalAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("industry", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=15)),
                ("name", models.CharField(max_length=30)),
                ("current_ratio", models.FloatField()),
                ("quick_ratio", models.FloatField()),
                ("cash_ratio", models.FloatField()),
                ("debt_equity", models.FloatField()),
                ("inventory_turnover", models.FloatField()),
                ("days_inventory", models.FloatField()),
                ("assets_turnover", models.FloatField()),
                ("roe", models.FloatField()),
                ("net_margin", models.FloatField()),
                ("per", models.FloatField()),
                ("pcf", models.FloatField()),
                ("ps", models.FloatField()),
                ("pbv", models.FloatField()),
                ("per_five_years", models.FloatField()),
                ("ps_five_years", models.FloatField()),
                ("pbv_five_years", models.FloatField()),
                (
                    "fundamental_analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stock_report.fundamentalanalysis",
                    ),
                ),
            ],
        ),
    ]
