# Generated by Django 4.1.5 on 2023-01-24 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FundamentalAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("industry", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=15)),
                ("name", models.CharField(max_length=30)),
                ("current_ratio", models.FloatField(default=0)),
                ("quick_ratio", models.FloatField(default=0)),
                ("cash_ratio", models.FloatField(default=0)),
                ("debt_equity", models.FloatField(default=0)),
                ("inventory_turnover", models.FloatField(default=0)),
                ("days_inventory", models.FloatField(default=0)),
                ("assets_turnover", models.FloatField(default=0)),
                ("roe", models.FloatField(default=0)),
                ("net_margin", models.FloatField(default=0)),
                ("per", models.FloatField(default=0)),
                ("pcf", models.FloatField(default=0)),
                ("ps", models.FloatField(default=0)),
                ("pbv", models.FloatField(default=0)),
                ("per_five_years", models.FloatField(default=0)),
                ("ps_five_years", models.FloatField(default=0)),
                ("pbv_five_years", models.FloatField(default=0)),
                (
                    "fundamental_analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stock_report.fundamentalanalysis",
                    ),
                ),
            ],
        ),
    ]
