# Generated by Django 4.1.5 on 2023-01-24 02:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("stock_report", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fundamentalanalysis",
            name="last_update",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="stock",
            name="last_update",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="stock",
            name="stock_price",
            field=models.FloatField(default=0),
        ),
    ]
